import Head from "next/head";
import Navbar from "@/Components/Navbar";
import About from "@/Components/About";

import { Roboto } from '@next/font/google'
import Skills from "@/Components/Skills";
import Projects from "@/Components/Projects";
import AboutMe from "@/Components/AboutMe";
import Layout from "@/Components/Layout";
import ContactMe from "@/Components/ContactMe";
import Footer from "@/Components/Footer";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Vinay Selukar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={roboto.className}>
        <Navbar />
        <Layout>
        <About/>
        <AboutMe/>
        <Skills/>
        <Projects/>
        <ContactMe/>
        </Layout>
        <Footer/>
        </div>
    </>
  );
}
