import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Hello from "@/Components/hello";
import About from "@/Components/About";

import { Roboto } from '@next/font/google'
import Skills from "@/Components/Skills";

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function Home() {
  return (
    <>
      <Head>
        <title>Vinay Selukar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={roboto.className}>
        <Hello />
        <About/>
        <Skills/>
      </div>
    </>
  );
}
